### ISSUE TITLE
Is it possible to put charts before the pie chart, i.e. I want pie chart at the end of stats.

### ISSUE THREAD

**Issue by adix03** [matthayes/anki_progress_stats#14]

**Comment by matthayes** [comment]
Yea I think this is possible. I’ll look into this. It would be nicer I think.

**Comment by matthayes** [comment]
I released 0.12 which moves the graphs above the pie chart.  Check it out and let me know if you have more feedback.

**Comment by matthayes** [comment]
Change was in commit e58671de6a6fab94dc0e323b162376721b6811db
