### ISSUE TITLE
When timespan is chosen to be decklife, graph becomes useless

### ISSUE THREAD

**Issue by adix03** [matthayes/anki_progress_stats#15]
![Sketch](https://user-images.githubusercontent.com/51046583/59244512-7030a380-8c32-11e9-9d04-3b258d364443.png)

**Comment by matthayes** [comment]
Is there anything unusual about this deck? I don’t experience this issue so I’m thinking there is some corner case I didn’t anticipate. If you can share your deck somehow that’s help me reproduce it.

**Comment by matthayes** [comment]
Actually I found a deck of mine where I can reproduce this.  The deck where I can reproduce it is new for me.  My oldest review is only a couple months ago.  What about your deck?  Can you select "1 year" and share a screenshot of the graph?

It might be an Anki issue actually.  For me the built in graphs like Review Count and Review Time are also screwed up.  Is this the same for you?  I'll look at my code and see what I can do about this.  I'll probably also file an issue in the Anki support page.

**Comment by matthayes** [comment]
Okay I think I got to the bottom of this.  I'm still using Anki 2.0 (although the plugin does support 2.1 too).  The plugin is using the same logic as older Anki code that chooses the bucket size like below for deck life:

```
        num_buckets = None
        bucket_size_days = 30
```

If the oldest review is only a month or two ago then there will only be one or two buckets.  In your case it appears there is only one bucket.

When I view the problematic deck in Anki 2.1 I don't see the issue with Review Count and Review Time.   Looking at Anki's source code it now takes deck age into account.

So I should be able to get this fixed.  Thanks for filing the issue!

**Comment by adix03** [comment]
This is the link for my deck and anki stats pdfs
https://drive.google.com/open?id=1zRSMX7H_kMYC4xDGjGOsDg1wm2KOP9Ul

**Comment by matthayes** [comment]
Fix in 0800d1cf53ec4a490a181779bcb40d551c08393e.  Graphs now plot correctly in Anki 2.1.  In Anki 2.0 the bars are the same (consistent with other Anki graphs) but at least now the ticks are fixed to be consistent as well.
