### ISSUE TITLE
About counting the buried cards

### ISSUE THREAD

**Issue by Steven-AA** [matthayes/anki_progress_stats#19]
I am using the option of "bury related new cards until the next day". 
![image](https://user-images.githubusercontent.com/22387129/61587478-b710a200-abbd-11e9-9b45-aaed3831f515.png)
I want to moniter the number of buried cards to decide the speed of adding new cards. However, the number of buried cards can only see in the pie graph along with suspended cards after learned every card of Today.
![image](https://user-images.githubusercontent.com/22387129/61587489-c98adb80-abbd-11e9-8472-4c2d865f82e8.png)
Is there a better way to moniter the number of buried cards or to decided the speed of adding new cards?

Sorry for my poor English and Thanks a lot.

**Comment by matthayes** [comment]
I believe this is possible.  I looked at the Anki code a bit.  The "Suspended+Buried" stat in the pie chart comes from [here](https://github.com/dae/anki/blob/master/anki/stats.py#L723), which is computed [here](https://github.com/dae/anki/blob/master/anki/stats.py#L773).   This count is computed like so:

```
sum(case when queue<0 then 1 else 0 end) -- susp
```

According to [cards.py](https://github.com/dae/anki/blob/master/anki/cards.py#L16) the queue values are:

```
# Queue: same as above, and:
#        -1=suspended, -2=user buried, -3=sched buried
```

So in theory I think one could create a plugin that either alters how the pie chart is computed to break up this count or add a new pie chart/or something that shows the individual counts.  I think this may be out of scope for what I intended `anki_progress_stats` to be though.  I'm happy to review some code or add pointers if you want to try tackling this yourself though.

**Comment by Steven-AA** [comment]
Thanks a lot.
I'm not familiy with developing an anki plugin. But I will try when I have time.
