### ISSUE TITLE
has stopped tracking new learned cards despite matured cards feature working

### ISSUE THREAD

**Issue by anki1769** [matthayes/anki_progress_stats#20]
This worked fantastic for nearly a month, and I've really enjoyed it. About 2 weeks ago, it just stopped tracking newly learned cards despite me continually taking new cards each day. Here is a picture showing the issue. Thanks!
<img width="854" alt="Screen Shot 2019-10-21 at 7 16 04 PM" src="https://user-images.githubusercontent.com/56851123/67249882-48024e00-f437-11e9-825b-49694a183462.png">

**Comment by matthayes** [comment]
Interesting. Did anything of note change in the past couple weeks such as upgrading the version of Anki? Can you share which versions of Anki you are using? Also are you using the V2 scheduler or the original one?

**Comment by matthayes** [comment]
Would you be willing to export your deck and share it with me?  If so I can send you a link that you can use to share it with me privately.  This would help me figure out the issue much faster, assuming you're still having a problem with it.

**Comment by matthayes** [comment]
I'm going to close this for now.  If you are still having problems and can share some more info I'm happy to investigate.
