### ISSUE TITLE
Addon not working for me

### ISSUE THREAD

**Issue by jcznk** [matthayes/anki_progress_stats#28]
My Anki version is 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Below you can find my addon list. They are quite a lot, so don't feel obliged

1.	Add Cards – Web Browser
2.	Add Hyperlink
3.	Add Table
4.	Additional Card Fields Fork for 21
5.	AddonBackup
6.	Advanced Browser
7.	Advanced Copy Fields
8.	Anki Browser Context Menu Search
9.	Anki Simulator
10.	Anki Zoom
11.	AnkiWebView Inspector
12.	ANTI-SUCK automatically move leeches to a separate deck
13.	AutoDefine - Automatically define vocabulary words with pronunciations and image
14.	AwesomeTTS Google Cloud Text-to-Speech unofficial
15.	batch change fonts
16.	Batch Editing
17.	Batch Remove Formatting eg bold italics etc
18.	Blitzkrieg II - Advanced Browser Sidebar BETA7
19.	Browser Search Box Quick Insert Tag Deck Notetype
20.	Browser TableEditor side-by-side horizontal split
21.	Cacher In The Rye Windows Archived
22.	Change note type respect field and card names
23.	Click to replay animated Gifs
24.	Clickable Tags v20 Anki 2120 support
25.	Color Confirmation
26.	Colorful toolbars
27.	confirm deletion
28.	Customize Keyboard Shortcuts
29.	Customize Sidebar
30.	Deadline2
31.	Deck name in title 21
32.	Deck Stats
33.	Disable fading between cards
34.	Edit Field During Review Cloze
35.	editor - remove more formatting for selection headings hyperlinks
36.	editor apply font color background color custom class custom style
37.	Empty cards returns more usable informations
38.	Enhance main window
39.	Extended Card Stats During Review
40.	extended editor for templates with save and diff and html source of fields
41.	External Note Editor for the Browser
42.	Fast cards reposition
43.	Field History
44.	Field Modifier Random Item Fork for 21
45.	Frozen Fields
46.	GODMODE faster shortcuts and cloze switching
47.	Hanzi Stats
48.	Highlight Search Results in the Browser
49.	Holdem Cardfield Preserves add card history
50.	HoochieMama Randomize Rev Queue
51.	HoochiePapa Randomize New Queue
52.	Ignore accents in browser search
53.	Image Occlusion Enhanced for Anki 21 alpha
54.	Image Style Editor
55.	Improved Quizlet to Anki 21 Importer
56.	Increase autosave frequency
57.	Keep card displayed in reviewer until it is modified
58.	Kitten Rewards Gamification
59.	Knockout Deck Subset Learning
60.	link cardsnotes and preview them in extra window
61.	Long term backups
62.	LPCG LyricsPoetry Cloze Generator
63.	Maximum image height and width in card editor
64.	memrise2anki
65.	MIA Retirement
66.	Mini Format Pack
67.	More Overview Stats 21
68.	Open deck in browser from main window
69.	Oxford Dictionaries
70.	Pennywise Add Only Once Option
71.	Pop-up Wikipedia Beta
72.	Progress Graphs and Stats for Learned and Matured Cards
73.	Pull from Duolingo - Temporarily Broken by Recent Change to Duolingo
74.	Push Paradox Sibling Cardistry
75.	Quick Colour Changing
76.	Quick note and deck buttons Fork for 21
77.	Quick tagging 21
78.	rebuild allempty all filtered decks enhanced fork
79.	Refocus Card when Reviewing 21
80.	Remove card history
81.	Remove Cloze Button and Hotkey
82.	remove linebreaks  do word wrap fork for 21
83.	Replay buttons on card
84.	Review Heatmap
85.	Reviewer Context Menu Search
86.	Search and Replace Tags
87.	Separate Learn and Relearn in the Answer Buttons graph 21
88.	show_warning_if_no_tags_when_adding_cards
89.	Slackers Delight PostponeDefer Button
90.	Special Fields
91.	Statistics for Note Types Card Types and Tags
92.	Straight Reward
93.	Study Logger
94.	Symbols
95.	Symbols As You Type
96.	Tag Toggler Fork for 21
97.	Text Rendering Fix
98.	Toggle front and back card in Anki 21
99.	Touch Wood Show New Cards Left Hint
100.	Transfer scheduling data from one card to another
101.	True Retention by Card Maturity
102.	Undelete deleted note

**Comment by matthayes** [comment]
Is it feasible for you to test my plugin under the same conditions with your deck/collection without all the other plugins installed? Maybe on another computer? Installing that number of plugins would be time consuming so it’d be helpful if we knew it worked under the same conditions without all the plugins. Then we know it’s at least one of the other plugins causing incompatibility. Knowing that I could narrow it down.

**Comment by matthayes** [comment]
Also can you clarify what part is not working? Do the graphs not show up at all or is there an issue with how they look?

**Comment by jcznk** [comment]
The graphs do not show up at all. I tried removing all the other addon folders and now your plugin works fine!

**Comment by jcznk** [comment]
After some trial and error I believe the culprit should be "Separate Learn and Relearn in the Answer Buttons graph 21"

**Comment by matthayes** [comment]
Thanks for figuring this out!  I tested this too and can confirm that this plugin does cause the graphs in my plugin to not show up.  Looking at the [github page](https://github.com/Arthur-Milchior/anki-separate-buttons) this is a known issue.
