### ISSUE TITLE
Learned and mature cards not showing up

### ISSUE THREAD

**Issue by abdollahegazy** [matthayes/anki_progress_stats#31]
The stats that are supposed to be showing learned and matured cards are not popping up on my stats page. I am on Anki 2.1.35

**Comment by matthayes** [comment]
Can you confirm whether you are holding down the SHIFT key on your keyboard while you are clicking on the stats link?  Starting with the introduction of the new Anki stats page, the legacy page, to which these stats are added, is now access through this method.

**Comment by abdollahegazy** [comment]
Ah I was not, thank you very much.

**Comment by matthayes** [comment]
Okay great.  At some point I will migrate to the new page so you won't need to do that.
