### ISSUE TITLE
is there any way to get the remaining time of the deck?

### ISSUE THREAD

**Issue by ofou** [matthayes/anki_progress_stats#8]
I think I would be very useful and motivational having these stats, it works as learned and matured cards but in reverse. I mean, how many cards (in time) should I have to learn in order to finish this Deck?

**Comment by matthayes** [comment]
Thanks for the suggestion, that's a good idea.  I could try to predict how many more days it would take to learn the remaining cards in your deck given the recent average learning rate.

**Comment by matthayes** [comment]
Closing this as I probably won't end up implementing this.
